version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /docker-credentials/username
    DOCKER_PASSWORD: /docker-credentials/password
  variables: {}

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r CI-CD-demo/requirements.txt
  build:
    commands:
      - cd CI-CD-demo/
      - echo "Building Docker image"
      - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - docker build -t "docker.io/$DOCKER_USERNAME/demo-ci-cd:latest" .
      - docker push "docker.io/$DOCKER_USERNAME/demo-ci-cd:latest"
  post_build:
    commands:
      - echo "Build is successful"
